import { IMAGE_CONSTANTS } from '@constants/imageConstants';

export const SIGNUP_CONSTANTS = {
  TITLE_TEXT: {
    0: () => `반가워요!\n이름을 입력해 주세요`,
    1: (name) => `${name}님의\n생일을 입력해 주세요`,
    2: (name) => `${name}님의\n입대일을 입력해 주세요`,
    3: (name) => `${name}님의\n군종을 선택해 주세요`,
    4: (name) => `${name}님의\n자대를 선택해 주세요`,
    5: (name) => `${name}님의\n중대를 선택해 주세요`,
    6: (name) => `${name}님의\n소대를 선택해 주세요`,
    7: (name) => `${name}님의\n계급을 선택해 주세요`,
    8: (name) => `${name}님의\n군번을 입력해 주세요`,
    9: () => `안전한\n비밀번호를 입력해 주세요`,
    10: () => `안전한\n비밀번호를 확인해 주세요`,
  },
  PLACEHOLDER: {
    0: '이름을 입력하세요',
    1: '생일을 입력하세요 (YYYY-MM-DD)',
    2: '입대일을 입력하세요 (YYYY-MM-DD)',
    3: '군종을 선택하세요',
    4: '자대를 선택하세요',
    5: '중대를 선택하세요',
    6: '소대를 선택하세요',
    7: '계급을 선택하세요',
    8: '군번을 입력하세요',
    9: '8~16자리 영문, 숫자, 특수문자',
    10: '한번 더 입력해주세요',
  },
  LABEL: {
    0: '이름',
    1: '생일',
    2: '입대일',
    3: '군종',
    4: '자대',
    5: '중대',
    6: '소대',
    7: '계급',
    8: '군번',
    9: '비밀번호',
    10: '비밀번호 재확인',
  },
  IMGAE: {
    X: IMAGE_CONSTANTS.X,
    eye: IMAGE_CONSTANTS.EYE,
    noneye: IMAGE_CONSTANTS.TEXTHOLDER,
  },
  OPTIONS: {
    3: ['육군', '해군', '공군', '해병대'],
    7: ['이병', '일병', '상병', '병장', '간부'],
  },
  Text: {
    next: '다음',
  },
};
